feat: implementa ação de duplicação da entidade oportunidade
culturagovbr/mapadacultura pull request #23
Opened 2024-09-17 17:11 UTC by vicmagpac

## Descrição

Implementa regra de duplicação de oportunidade, fazendo com que se crie uma nova oportunidade baseado em uma oportunidade já existente, com todos os dados entre eles os da fases.

## Validação

Acessar a oportunidade e no footer de ações clicar no botão "Salvar modelo" em seguida deve abrir um modal de confirmação e ser redirecionado para a lista de oportunidade em rascunho com a nova oportunidade criada.

![Gravaodetelade30-07-2024134440-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/4945b035-587f-4b8a-a7a4-db9d335e92c6)

## Issues relacionadas

https://github.com/RedeMapas/mapas/issues/325

2024-09-20 16:39 UTC, PrezzotoMarianaCOSIS commented
Prezado Lucas Pirola e equipe TED-PR, conforme informado pelo Lucas por e-mail, da entrega desse PR#23 para validação, informo que o pedido de deploy do PR em ambiente controlado de testes (HMG do Mapa MinC) já está em andamento, o deploy sendo feito com sucesso iremos iniciar aqui internamente na COSIS a primeira bateria de testes funcionais da entrega. 

° validação funcional tem o objetivo de verificar o correto funcionamento da entrega/funcionalidade no ambiente de teste, se a evolução/melhoria proposta na entrega realmente se comporta da maneira informada.

2024-09-24 12:19 UTC, lpirola commented
Obrigado pelo retorno, estamos à disposição para qualquer dúvida.

2024-09-24 19:07 UTC, PrezzotoMarianaCOSIS commented
Boa tarde Lucas Pirola e equipe TED-PR, informo que ontem (dia 23/09) foram realizados os testes funcionais, em ambiente HMG do Mapa, da entrega desse PR 23 - duplicação da entidade oportunidade.

Em termos operacionais da funcionalidade que se apresenta no Frontend, informamos que está funcionando plenamente - sem erros e atende o que foi proposto, sendo :

- A oportunidade é duplicada, "clonada" por inteiro - copia as fases, os arquivos anexados, os avaliadores que estavam cadastrados para aquela oportunidade duplicada e também duplica os administrados daquela oportunidade, como se fosse um espelho mesmo.

- Quando clicamos em Duplicar oportunidade, um rascunho da oportunidade duplicada é gerado e vai para a caixa do gestora/administrador do edital, lá no painel de controle dele - nas oportunidades geradas por ele, e dali ele pode continuar a editar aquela oportunidade que ele duplicou. 

- A funcionalidade de duplicação da entidade oportunidade somente pode ser usada pelo Administrador/Gestor daquele Edital, ou seja, um usuário que não é gestor/dono daquele edital não pode duplicar um edital que ele não é administrador.

Sendo assim em termos operacionais da funcionalidade em como se comporta perante ao usuário no Frontend está ok, ENTRETANTO, observamos a necessidade de ajuste relativo a forma de codificação em termos de Backend, dessa Duplicação da oportunidade, mais especificamente a parte de duplicação e cópia dos arquivos que foram também duplicados, conforme disposto abaixo:

- Fizemos uma conferencia interna no código na forma como essa funcionalidade de duplicar foi implementada, **se esses arquivos foram duplicados como cópias independentes no disco**, haja visto que a oportunidade "nova duplicada" não deve aproveitar o arquivo já gravado pela oportunidade "original". Pois caso seja necessário alterar um arquivo da oportunidade "nova duplicada", esse arquivo não sendo uma cópia independente no disco, irá alterar e impactar o arquivo já gravado pela oportunidade "original". Essa implementação, feita dessa forma (arquivo duplicado não sendo uma cópia independente no disco), muda uma premissa do sistema, de que cada oportunidade tenha seus próprios anexos de maneira independente.

- Essa verificação concluiu que de fato a implementação feita aqui no PR 23 direciona os arquivos da oportunidade duplicada para o mesmo arquivo em disco, eles não estão sendo duplicados como cópias independentes no disco.

**SOLICITAÇÃO DE AJUSTE DO PR**: 

- Solicitamos que os arquivos sejam fisicamente copiados na duplicação da oportunidade - arquivos devem ser duplicados como cópias independentes no disco. Ajuste a ser feito a nível de comando de código, Backend. 

Sendo assim ficamos no aguardo desse ajuste na entrega, peço informar aqui nos comentários quando esse ajuste estiver pronto para refazermos o deploy em HMG e realizarmos novamente os testes nesse sentido.

Caso precisem de uma reunião para maior detalhamento do ajuste solicitado por essa COSIS/STII peço informarem para agendarmos.

2024-09-24 19:50 UTC, PrezzotoMarianaCOSIS commented
Segue em anexo arquivos PNG com as imagens evidenciando a questão reportada no ajuste solicitado:

- arquivos-clonados-bd
- arquivos-clonados-tela

SOLICITAÇÃO DE AJUSTE DO PR:

Solicitamos que os arquivos sejam fisicamente copiados na duplicação da oportunidade - arquivos devem ser duplicados como cópias independentes no disco. Ajuste a ser feito a nível de comando de código, Backend.
![arquivos-clonados-bd](https://github.com/user-attachments/assets/60b1a33d-c3c1-47b6-919d-11dbf05a0dda)
![arquivos-clonados-tela](https://github.com/user-attachments/assets/9e1587ff-572f-4ab4-abb6-cf0d1b3ecdc2)

2024-09-24 21:14 UTC, vicmagpac commented
> Segue em anexo arquivos PNG com as imagens evidenciando a questão reportada no ajuste solicitado:
> 
> * arquivos-clonados-bd
> * arquivos-clonados-tela
> 
> SOLICITAÇÃO DE AJUSTE DO PR:
> 
> Solicitamos que os arquivos sejam fisicamente copiados na duplicação da oportunidade - arquivos devem ser duplicados como cópias independentes no disco. Ajuste a ser feito a nível de comando de código, Backend. ![arquivos-clonados-bd](https://private-user-images.githubusercontent.com/151965166/370443961-60b1a33d-c3c1-47b6-919d-11dbf05a0dda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMDc3MDQsIm5iZiI6MTcyNzIwNzQwNCwicGF0aCI6Ii8xNTE5NjUxNjYvMzcwNDQzOTYxLTYwYjFhMzNkLWMzYzEtNDdiNi05MTlkLTExZGJmMDVhMGRkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxOTUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmQ1OTZlOThlYmI1ZmZhZjUwZmU0YjE0MWJjYTQwZTE4ZDBmMmJhOGQ4ZDMyZTllZTU2YzczMDhkNTZkNDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XAmmwXNyc95rpM8GLR2fG6KrcqKPcv01oF_u8ilyxqk) ![arquivos-clonados-tela](https://private-user-images.githubusercontent.com/151965166/370444007-9e1587ff-572f-4ab4-abb6-cf0d1b3ecdc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMDc3MDQsIm5iZiI6MTcyNzIwNzQwNCwicGF0aCI6Ii8xNTE5NjUxNjYvMzcwNDQ0MDA3LTllMTU4N2ZmLTU3MmYtNGFiNC1hYmI2LWNmMGQxYjNlY2RjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxOTUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWU5ZTNhYjg0MzViODM5OWI4ZThiZDcyMjkzODhjN2ZmMGU0MmFhMmFmZDlkZjU3ZmQ3ZmE2ZThmZGQzNWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I0amlAKCZNtwUc_cSmsHOV5JhbkLqg8xTXONavBfzhs)

Obrigado pelo retorno.

Penso que talvez faz sentido desabilitar esse trecho de duplicar os arquivos, no aspecto que cada oportunidade pode ter um modelo diferente de arquivos, tanto a nível de imagens como a nível de documento, fazendo assim a duplicação (cópia) especificamente da estrutura das oportunidades e suas fases. Faz sentido?

2024-09-25 01:22 UTC, vicmagpac commented
Realizamos a atualização para que os arquivos sejam duplicados e que as referência sejam para os arquivos duplicados tanto no banco como também no public files.

2024-09-25 20:18 UTC, PrezzotoMarianaCOSIS commented
Informo que estamos rodando novamente o deploy do PR em ambiente controlado de testes (HMG do Mapa MinC) para verificação do ajuste feito. Informo assim que verificarmos se está ok. 

Obrigado pelo retorno @vicmagpac

2024-09-26 20:30 UTC, PrezzotoMarianaCOSIS commented
Venho oficializar que esse PR  #23 está validado e homologado na data de hoje (26/09) por ambas equipes competentes: COSIS e SGE (MinC). 

- o ajuste solicitado quanto aos arquivos serem fisicamente copiados na duplicação da oportunidade foi testado e está conforme.

@fernandolordao peço proceder com a integração e incorporação desse PR na branch principal do MinC.

2024-09-30 03:23 UTC, fernandolordao commented on src/core/Traits/EntityOpportunityDuplicator.php
> +            $parentId = $file['parent_id'];
Prezados, bom dia!

Parabenizo os ajustes implementados e gostaria de solicitar tratamento para o possível cenário inconsistente onde `!isset($futureParentId) && !is_null($file['parent_id'])`, o qual ocorreria se, na primeira iteração do `foreach`, já nos deparássemos com `parent_id` preenchido.

É importante cobrir este cenário para garantir completo tratamento dos casos possíveis, mesmo os inesperados, exatamente para facilitar providências em caso de inconsistência.

Para isso, proponho a refatoração das linhas 204 a 207 conforme segue:
```
            if (is_null($file['parent_id'])) {
                $parentId = null;
            } else if (isset($futureParentId) {
                $parentId = $futureParentId;
            } else {
                // TODO: implementar tratamento conveniente para este caso de inconsistência. Por exemplo: lançar uma exceção específica, digamos UnexpectedParentAtFirstPlace.
            }
```

2024-09-30 14:01 UTC, vicmagpac commented on src/core/Traits/EntityOpportunityDuplicator.php
> +            $parentId = $file['parent_id'];
Obrigado pelo retorno Fernando.

Realizamos a atualização em um novo commit adicionando a condição informada acima.

O exemplo abaixo mostra o grp avatar, onde o avatar primário deve ser null e os tamanhos dos avatar (small, medium e big) dependem do avatar primário referenciando via id do registro. No path a atualização acontece o mesmo, onde é concatenado com id da oportunidade e id do parent id do arquivo.

![image](https://github.com/user-attachments/assets/eae18e9e-5081-4c7a-a836-34ff0617167e)

O commit atualizado está aqui: https://github.com/culturagovbr/mapadacultura/pull/23/commits/07120eb21e667c00f0a0880b8ca66bc5079ed28f

2024-09-30 17:52 UTC, fernandolordao-minc commented on src/core/Traits/EntityOpportunityDuplicator.php
> +            $parentId = $file['parent_id'];
@vicmagpac eu entendi que o primeiro elemento deve ter `$file['parent_id']` nulo e, em caso de normalidade, quando se opera com `$file['parent_id']` preenchido já temos `$futureParentId` preenchido.

Minha sugestão é abortar/desfazer a duplicação, ou, ao menos, alertar se o primeiro elemento não existir (caso de inconsistência), situação em que o `$parentId` ficaria sem preenchimento ou com preenchimento indevido.

Nesse sentido, minha sugestão de menor esforço foi terminar os IFs com um ELSE que lança uma exceção (ver meu comentário anterior). Como você deixou sem isso, poderia me mostrar como fica o tratamento?

Perceba que estou falando de um caso de inconsistência, não é a situação normal, devida e esperada. E me preocupo com isso agora porque depois que esse código estiver em produção e essa inconsistência eventualmente ocorrer, ninguém mais lembrará desse detalhe e a mera identificação do problema pode tomar um tempo que pode ser evitado com um pequeno esforço agora. Entende minha preocupação?

2024-09-30 18:30 UTC, vicmagpac commented on src/core/Traits/EntityOpportunityDuplicator.php
> +            $parentId = $file['parent_id'];
@fernandolordao adicionei uma exception caso quando o parent id seja nulo ou vázio.

2024-09-30 19:59 UTC, fernandolordao commented on src/core/Traits/EntityOpportunityDuplicator.php
> +            } else if (isset($futureParentId) && !is_null($file['parent_id'])) {
@vicmagpac na linha 207, sugiro remover o termo ` && !is_null($file['parent_id'])`, pois, neste ponto, este termo sempre será verdadeiro e podemos simplificar a expressão lógica em favor da manutenibilidade do código.

2024-09-30 20:04 UTC, fernandolordao commented on src/core/Traits/EntityOpportunityDuplicator.php
> +                throw new Exception('File parent_id is null or not exists');
Quando o `parent_id` for nulo, o IF executará primeira condição, logo, neste ponto (linha 210), `parent_id` sempre vem preenchido e não podemos dizer que é nulo ou inexistente. Assim, sugiro a mensagem 'File parent_id unexpect'.

Me perdoe pelos vários comentário, mas você teria outro ponto de vista, @vicmagpac ?

2024-10-01 01:23 UTC, fernandolordao-minc requested changes

2024-10-01 01:23 UTC, fernandolordao-minc commented on src/core/Traits/EntityOpportunityDuplicator.php
> +                throw new Exception('File parent_id unexpect');
Corrigir grafia para "unexpected".

2024-10-02 12:50 UTC, lpirola commented on src/core/Traits/EntityOpportunityDuplicator.php
> +                throw new Exception('File parent_id unexpect');
corrigido @fernandolordao-minc

2024-10-04 18:03 UTC, fernandolordao-minc approved these changes

2024-10-04 18:04 UTC, fernandolordao commented
Modificações aprovadas. Aguardando nova rodada de testes, considerando que houve mudança no código.

2024-10-08 00:33 UTC, merged

2024-10-08 01:43 UTC, fernandolordao commented
### Observações para providência posterior

* Data e hora de criação e atualização (_**create_timestamp**_ e _**update_timestamp**_) da nova oportunidade preenchidos sem uniformização. Maior parte dos preenchimentos assumiram o valor corrente (data/hora do momento da operação, no exemplo foi 2024-10-08), enquanto que a coluna _**create_timestamp**_ no primeiro registro, no terceiro e nos posteriores, assumiram o preenchimento da oportunidade original (no exemplo foi 2024-09-12), conforme imagem seguinte.
![datahora_sem_padrao](https://github.com/user-attachments/assets/301eeb61-2fa2-4400-a6ca-41dea3698ea1)
**PROVIDÊNCIA SUGERIDA:** garantir que todos os preenchimentos de data e hora assumam a data e hora do momento da operação.

* Caso o navegador tenha bloqueio de popups, o processamento (mesmo sendo bem-sucedido) fica congelado com a mensagem “Duplicando oportunidade” (ver rodapé da captura a seguir) em vez de conduzir à tela de “Minhas oportunidades > Em rascunho”.
![duplicando_a_entidade](https://github.com/user-attachments/assets/50299260-29f2-45e7-bb64-e987f6825a3e)
**PROVIDÊNCIA SUGERIDA:** ocultar o label “Duplicando a entidade” antes do redirecionamento e avaliar alternativas para minimizar a chance de duplicações desnecessárias por compreensão equivocada por parte da pessoa que opera.