feat: Implementa funcionalidade de gestão de modelos
culturagovbr/mapadacultura pull request #24
Opened 2024-09-20 13:29 UTC by vicmagpac

## Descrição

Implementa funcionalidades de gestão de modelos de oportunidades.

- Criar modelo baseado em uma oportunidade
- Listagem de modelos com os detalhes de (tipo, tempo de execução, proponentes)
- Permite criar uma oportunidade baseado em um modelo predefinido.

## Validação

Acessar a oportunidade e no footer de ações clicar no botão "Salvar modelo" em seguida deve abrir um modal para ser especificado o nome do modelo e a descrição, ao confirmar deve ser redirecionado para a lista de "meus modelos" dentro do gerenciamento de oportunidades.

2024-09-20 17:42 UTC, lpirola commented
@fernandolordao fizemos uma demonstração no final dessa transmissão, pode ajudar a entender como a funcionalidades está documentada.

https://www.youtube.com/watch?v=eP3hJMm-zeo

2024-09-20 20:03 UTC, PrezzotoMarianaCOSIS commented
Oficializo o recebimento provisório desse PR e informo que primeiro estamos no processo de validação funcional, em ambiente de teste do Mapa, do #23 entregue oficialmente dia 18/09 (deploy Central MinC ticket 30187).

Após validação do #23 partiremos para deploy e validação em ambiente de testes desse PR aqui disposto, pois cada PR (branch isolada da tarefa) será validada em ambiente controlado de teste do Mapa da Cultura MinC e integrada após validação na branch develop-minc separadamente.

2024-09-28 01:36 UTC, PrezzotoMarianaCOSIS commented
Informo que foi realizado, ao meio dia de hoje (27/09) o deploy do PR #24  em ambiente controlado de testes (HMG do Mapa MinC) e já está em andamento, aqui internamente na COSIS, a primeira bateria de testes funcionais da entrega.

Testes funcionais estando ok, será realizado a validação negocial pela SGE. 

- validação funcional tem o objetivo de verificar o correto funcionamento da entrega/funcionalidade no ambiente de teste, se a evolução/melhoria proposta na entrega realmente se comporta da maneira informada.

- validação negocial tem o objetivo de atestar se a entrega realmente condiz com a necessidade do negócio e com o alinhado como produto para a área gestora da TED – SGE.

2024-10-08 21:36 UTC, fernandolordao requested changes
Ver comentários no código. Ainda falta revisão de alguns arquivos que poderão gerar novas solicitações de ajuste.

2024-10-08 21:36 UTC, fernandolordao commented on src/modules/Entities/components/opportunity-create-based-model/script.js
> +                mess = this.text('Todos os campos são obrigatorio');
```suggestion
                mess = this.text('Todos os campos são obrigatórios.');
```

2024-10-08 21:36 UTC, fernandolordao commented on src/modules/Entities/components/opportunity-create-based-model/script.js
> +                this.messages.success(this.text('Aguarde, estamos gerando a oportunidade baseada no modelo.'), 6000);
```suggestion
                this.messages.success(this.text('Aguarde. Estamos gerando a oportunidade baseada no modelo.'), 6000);
```

2024-10-08 21:36 UTC, fernandolordao commented on src/core/Traits/EntityManagerModel.php
> +        }
Garantir que neste `foreach` haja apenas modelos e eliminar necessidade do `if`.
```suggestion
        foreach ($opportunities->getResult() as $opportunity) {
            $opp = $app->repo('Opportunity')->find($opportunity['id']);
            $phases = $opp->phases;

            $lastPhase = array_pop($phases);

            $modelIsOfficial = false;
            foreach ($opp->getSealRelations() as $sealRelation) {
                if ( in_array($sealRelation->seal->id, $app->config['app.verifiedSealsIds'])) {
                    $modelIsOfficial = true;
                }
            }
            
            $days = !is_null($opp->registrationFrom) && !is_null($lastPhase->publishTimestamp) ? $lastPhase->publishTimestamp->diff($opp->registrationFrom)->days . " Dia(s)" : 'N/A';
            $tipoAgente = $opp->registrationProponentTypes ? implode(', ', $opp->registrationProponentTypes) : 'N/A';
            $dataModels[] = [
                'id' => $opp->id,
                'numeroFases' => count($opp->phases),
                'descricao' => $opp->shortDescription,
                'tempoEstimado' => $days,
                'tipoAgente'   =>  $tipoAgente,
                'modelIsOfficial' => $modelIsOfficial
            ];
        }
```

2024-10-08 21:36 UTC, fernandolordao commented on src/core/Traits/EntityManagerModel.php
> +                MapasCulturais\Entities\Opportunity op
Recuperar apenas os registros que são modelo, otimizando o processamento. Isso faz muito diferença para o Ministério, pois há milhares de oportunidades cadastradas em escopo nacional.
```suggestion
            SELECT 
                op.id
            FROM
                MapasCulturais\Entities\Opportunity op
            WHERE
                op.isModel = 1
```

2024-10-08 21:36 UTC, fernandolordao commented on src/modules/Entities/components/opportunity-create-based-model/texts.php
> +    'Todos os campos são obrigatorio' => i::__('Todos os campos são obrigatorio'),
```suggestion
    'Todos os campos são obrigatórios.' => i::__('Todos os campos são obrigatorio'),
```

2024-10-08 21:36 UTC, fernandolordao commented on src/modules/Entities/components/opportunity-create-based-model/texts.php
> +    'Aguarde, estamos gerando a oportunidade baseada no modelo.' => i::__('Aguarde, estamos gerando a oportunidade baseada no modelo.'),
```suggestion
    'Aguarde. Estamos gerando a oportunidade baseada no modelo.' => i::__('Aguarde, estamos gerando a oportunidade baseada no modelo.'),
```

2024-10-08 21:36 UTC, fernandolordao commented on src/modules/Entities/components/opportunity-create-model/texts.php
> +    'Todos os campos são obrigatorio' => i::__('Todos os campos são obrigatorio'),
```suggestion
    'Todos os campos são obrigatórios' => i::__('Todos os campos são obrigatórios'),
```

2024-10-15 02:54 UTC, PrezzotoMarianaCOSIS commented
Somando aos ajustes e considerações colocadas pelo Fernando quanto a esse PR, seguem abaixo mais pontos observados para ajustes e verificações após testes funcionais e verificações de código e banco feitas pela COSIS do MinC:

**1 - Modelo - Data e hora de criação e atualização** (_create_timestamp_ e _update_timestamp_) da nova oportunidade preenchidos sem uniformização. Maior parte dos preenchimentos assumiram o valor corrente (data/hora do momento da operação, no exemplo foi 2024-10-04), enquanto que a coluna _create_timestamp_ no primeiro registro assumiu o mesmo valor do edital original (no exemplo foi 2024-09-03), conforme imagem seguinte:

![Modelo - Data e hora de criação e atualização - tabela de banco](https://github.com/user-attachments/assets/5dd7bd90-32eb-4901-bf5c-e683dda2519e)

ALTERAÇÃO SOLICITADA: garantir que todos os preenchimentos de data e hora assumam a data e hora do momento da operação. ATENÇÃO: verificar oportunidades com mais fases, como do exemplo https://github.com/culturagovbr/mapadacultura/pull/23#issuecomment-2398450560.

**2 - Verificamos a criação do metadado “considerQuotasInGeneralList”** que aparentemente não está relacionado à operação de criar modelo.

![metadado “considerQuotasInGeneralList”](https://github.com/user-attachments/assets/2f11b39c-a004-4df7-a969-8cf157fc6001)

ALTERAÇÃO SOLICITADA: manter no modelo criado apenas os metadados originais existentes na oportunidade em questão.

**3 - Demora excessiva para renderizar cards com informações dos modelos criados** (tipo, fases, tempo etc). Ao criar o modelo ele aparece no painel de gestão do gestor que criou – print abaixo – e fica assim em branco durante aproximadamente 44 segundos até que os dados do Modelo apareçam de fato – segundo prints abaixo:

![Demora na renderização do Detalhamento do Modelo 1](https://github.com/user-attachments/assets/73556210-b8d2-4bc7-a1ac-36ae20dd3f03)

![Demora na renderização do Detalhamento do Modelo 2](https://github.com/user-attachments/assets/43adce55-fb73-4706-b1b9-e9ec0dc100fb)

ALTERAÇÃO SOLICITADA: processar apenas os modelos sem carregar todos as oportunidades (ver comentário no código).

**4 - Correções mais simples de caráter meramente ortográfico. Ver comentários diretamente no código feitas pelo Fernando**.

**5 - Quanto a parte específica de tornar o Modelo Oficial se a oportunidade original estiver relacionada ao selo verificado da plataforma**, foram realizados vários testes pela equipe COSIS e em específico um teste em tempo real em conjunto com a equipe TED-UFPR em reunião dia 08/10 com o Lucas Pirola e Vitor, seguem as considerações abaixo: 

- Não conseguimos validar os testes no ponto específico de tornar o Modelo Oficial se a oportunidade original estiver relacionada ao selo verificado da plataforma, testamos com o Selo Oficial verificado que existe na plataforma atualmente, Selo 1 - Selo Mapas (print abaixo), fazendo todo o processo conforme dispõe requisito:

![Selo Oficial Verificado - Selo 1 - Selo Mapas](https://github.com/user-attachments/assets/63744c36-bf7b-4b64-97f0-4a5e51ee010e)

- Primeiro, vinculamos a oportunidade original (que seria alvo da criação do modelo oficial) com o Selo 1 - Selo Mapas - Print abaixo (marcado de vermelho - Verificações).

![Oportunidade original com o selo verificado associado](https://github.com/user-attachments/assets/1ba1571a-f552-42ee-86ef-9826e0b8c1f9)

- Após isso, clicamos no botão Salvar Modelo para geração desse Modelo com base nessa oportunidade original. Print abaixo.

![Oportunidade original com o selo verificado associado - Salvar Modelo](https://github.com/user-attachments/assets/89cbde3b-e29d-4fa7-80df-d9582b542561)

- Tudo isso fazendo no perfil correto de administrador.

- Ao ir no painel de controle, em Minhas Oportunidades, em Meus modelos, aparece o Modelo criado, é possível tornar ele público, mas não aparece o termo Modelo Oficial como deveria aparecer no detalhamento do modelo, no print abaixo é possível verificar que essa informação de modelo oficial não aparece no modelo e deveria já estar aparecendo, pois conforme descrição da funcionalidade, se a oportunidade original já está com o selo verificado, ao criar o Modelo dela ele já é criado como essa informação diferenciada de Modelo Oficial em sua descrição, o que não ocorreu.
Modelo criado, mas sem a informação de Modelo Oficial como deveria aparecer junto com os outros detalhamentos do Modelo.

![Modelo que deveria ser OFICIAL - Informação de Modelo Oficial não aparece](https://github.com/user-attachments/assets/d0c2f34c-f8c8-4caf-b910-5206511e8be5)

- É possível observar que dentro do Modelo - print abaixo (após clicar em Usar modelo), também em Verificações, o selo verificado está lá, foi migrado para o Modelo, mas na tela do Modelo Criado - em Minhas Oportunidades, em Meus modelos, no detalhamento dele, não tem a informação de Modelo Oficial como deveria ter.
Dentro do Modelo criado - Usar Modelo - aparece o Selo verificado, sinal de que o selo verificado foi migrado do original para o Modelo. Mas mesmo assim ele não se tornou Modelo Oficial com essa informação clara em seu detalhamento, como colocado no print mais acima. 

![Modelo com o Selo Verificado - Usando o Modelo](https://github.com/user-attachments/assets/88c22e98-72c9-41f8-be61-2e980d4af48d)

- No print abaixo também é possível observar informações do selo e a oportunidade original que está relacionada (aparece essa tela quando clicamos no selo dentro da oportunidade original)

![Informações do selo verificado e a oportunidade original que está relacionada](https://github.com/user-attachments/assets/d2c81ca9-d55d-4cf4-bbd5-58bec1f60300)

- O Selo verificado existe, a interface reconhece como Selo verificado, se a interface reconhece, o sistema é capaz de reconhecer, e se o sistema reconhece esse selo verificado, então essa funcionalidade que está sendo implementada também possui capacidade de reconhecer, só precisa ser ajustada para isso. 

- Deve ser especificado claramente nessa entrega quais os critérios que permitem que esse Modelo seja reconhecido como Oficial, uma questão de especificação mais clara mesmo, tipo essa funcionalidade para funcionar corretamente depende de tabela X ter valor X, coluna Y ter valor Y, informar tudo que for requisito técnico para essa parte do Modelo Oficial funcionar corretamente, pois não ficou especificado neste nível de detalhe para ser entendido de forma clara porque não está funcionando, haja visto o Modelo ter sido gerado de uma oportunidade original que possui associado a ela um selo verificado (conforme os prints já colocados aqui) e mesmo assim o Modelo não fica com informação em seu detalhamento de Modelo Oficial. 

- Precisamos entender de forma mais clara quais são esses requisitos técnicos entregues para que essa parte funcione corretamente e assim possamos em conjunto ajustar e corrigir para funcionar no Mapa da Cultura MinC.

- Segundo informado em reunião dia 08/10 com o Lucas Pirola e Vitor da TED-UFPR essa funcionalidade não iria funcionar quando a aplicação Mapa possui configuração de subsites, mas essa hipótese não foi confirmada e deve ser melhor investigada, mas caso se confirme, precisa ser ajustado para funcionar com a configuração de subsites, pois a entrega do PR é para ser funcional e integrado no Mapa da Cultura MinC que possui subsites já confirmados como rede cultura viva e futuramente o subsite de Bibliotecas do MinC. 

**Sendo assim, é necessário a realização das verificações e ajustes solicitados nesse PR, tanto relativo ao disposto nesse comentário quanto aos comentários dispostos pelo Fernando quanto ao código. Caso necessitem de reunião para entender melhor as disposições colocadas nos informem**.

2024-10-15 04:42 UTC, lpirola commented
@PrezzotoMarianaCOSIS agradeço o esforço em detalhar de forma tão completa os diversos destaques que merececem nossa atenção para correção. Tão logo tenhamos feito as correções e os testes, serão avisados.

Sobre o refinamento dos requisitos e critérios de aceitação dessa atividade, podemos tratar no momento mais oportuno para disctutirmos melhor a abrangência do escopo dessa funcionalidade.

2024-10-16 21:19 UTC, lpirola commented
@fernandolordao @PrezzotoMarianaCOSIS conforme solicitado em reunião, a solução para esconder o aviso ao editar o modelo de oportunidades, foi implementada e já está disponível.

a solução para o botão sair, é mais complexa como eu havia adiantado e queremos decidir juntos como vamos preceder. Desabilito a funcionalidade de editar a oportunidade ou deixamos como está?

2024-10-16 21:42 UTC, fernandolordao approved these changes

2024-10-16 22:00 UTC, fernandolordao commented
Alterações atendidas. Integração pendente da seguinte definição sobre ajustes a serem realizados na Gestão de Modelo:

**OPÇÃO A -** Manter como está (ver imagem seguinte).
**OPÇÃO B -** Desabilitar a edição de modelos (atualmente acessível apenas para pessoas com permissão, clicando sobre o título do modelo).
**OPÇÃO C -** Manter a edição de Modelos, porém ajustando dois elementos: (1) ocultar tarja no topo do página e (2) incluir o botão Sair (ver imagem seguinte).

![edicao-de-modelo](https://github.com/user-attachments/assets/8c286798-baeb-4a1c-b645-afedcd3a0d92)

Aguardemos posicionamento da @PrezzotoMarianaCOSIS

2024-10-17 00:33 UTC, PrezzotoMarianaCOSIS commented
**Boa Noite @lpirola e @fernandolordao, quanto a ocultar tarja no topo do página, como colocou o Lucas no comentário dele logo mais acima, já foi feita, então esse ponto, da tarja no topo do página, já foi resolvido, pois era mais simples - @fernandolordao preciso apenas que rode o deploy novamente desse PR para eu conferir isso, mas acredito que está OK conforme informou o Lucas, sendo ponto encerrado e feito**.

**Quanto a questão do botão sair, por ser mais complexo não vejo necessidade e urgência de sua configuração agora, e comunico aos dois que iremos partir para OPÇÃO A - Manter como está**. Se trata de uma excelente funcionalidade entregue, que está restrita exclusivamente ao gestor/administrador daquele modelo, vejo como necessária e de valor para o MinC e não há necessidade de desabilitar essa edição somente por conta de um botão Sair, que não é de extrema necessidade para o funcionamento dessa edição, podendo o Gestor apenas clicar em voltar para sair da edição. **Podemos manter como está**.

**Solicito portanto @fernandolordao que assim que possível inicie a integração desse PR de forma definitiva na branch oficial do MinC para posterior deploy da TAG em produção**.

_PR aprovado e validado pela COSIS/STII/MinC_.

**OBS**: Ainda essa semana irei demonstrar essa funcionalidade em HMG para a gestora Juliana Almeida da SGE, o que não impede nossa aprovação aqui e integração e incorporação, haja visto estar funcional, com todos os ajustes solicitados realizados e conforme a necessidade do negócio.

2024-10-17 17:51 UTC, merged