Implementa integração do plugin do metabase dashboard compatível com versão v7.6.0
culturagovbr/mapadacultura pull request #39
Opened 2024-12-19 15:28 UTC by vicmagpac

### Importante 

Estamos criando um novo PR do plugin, no aspecto em que foram realizadas melhorias e principalmente garantindo a compatibilidade para a versão v7.6.0.

## Descrição

O PR tem como objetivo realizar a integração do plugin do metabase dashboard que é um fork do plugin oficial do metabase do mapas culturais que pode ser acessado no link https://github.com/RedeMapas/plugin-Metabase. O plugin é instalado através do gitsubmodule.

## Principais implementações no plugin:

- Adiciona hooks na search da entidade agente para adicionar os cards de quantitativos
![image](https://github.com/user-attachments/assets/cd2e0567-36ea-475a-b30e-b8a96de694a7)

- Adiciona hooks na search da entidade espaço para adicionar os cards de quantitativos
![image](https://github.com/user-attachments/assets/47e2cbe0-2c5e-40c8-9b45-4858358d5d33)

- Adiciona hooks na search da entidade oportunidade para adicionar os cards de quantitativos
![image](https://github.com/user-attachments/assets/f90f1e43-489b-4ef6-925b-9b811c2b59f7)

- Adiciona hooks na search (tab indicadores) da entidade agente para adicionar o dashboard
![image](https://github.com/user-attachments/assets/2d442569-16fd-4e44-ba6d-7bd3d30fb092)

- Adiciona hooks na search (tab indicadores) da entidade espaço para adicionar o dashboard
![image](https://github.com/user-attachments/assets/81e1c9af-14aa-4512-bab0-361b068bb415)

- Adiciona hooks na search (tab indicadores) da entidade oportunidade para adicionar o dashboard
![image](https://github.com/user-attachments/assets/b4dd7773-74fe-4f02-a2a8-77578a5f3010)

- Cards de indicadores da instância na página home
![image](https://github.com/user-attachments/assets/5f1151bb-e406-43a2-85f3-f1e2cd436c27)

- Página com todos os painéis de dados previamente configurado no ambiente
![image](https://github.com/user-attachments/assets/6fb4f14b-2824-40e9-9bd8-457cb5ba5117)

- Lista de painéis do ambiente
![image](https://github.com/user-attachments/assets/50c7c645-299a-4bcf-a34b-72ce37968935)

## Observação

Os arquivos de configuração podem ser encontrados em config/Metabase.php para o ambiente de produção e para o ambiente de desenvolvimento se encontra em dev/config.d/Metabase.php

Nas imagens acima mostram os dados de um ambiente de teste. Os dados dos cards na página home e na página das entidades (agente, espaço e oportunidade) são dados da própria instância que podem ser configuradas no arquivo de configuração em config/Metabase.php

Referente aos dashboard das entidades, as mesmas são também adicionadas no arquivo config/Metabase.php apontando para os links do dashboard público.

Exemplo de como adicionar/atualizar/remover um dashboard: 

```php
'links' => [
    'painel-agentes' => [
        'link' => 'https://metabase.mapas.tec.br/public/dashboard/898173be-47ae-4987-894c-b7e54914539c', // dashboard dos agentes
        'text' => 'Saiba os números de agentes individuais cadastrados, quantos são criados mensalmente, por onde estão distribuídos no território e outras informações.',
        'title' => 'Painel sobre agentes individuais',
        'entity' => 'Agent'
    ],
    'painel-espacos' => [
        'link' => 'https://metabase.mapas.tec.br/public/dashboard/ea36c1b3-c3f3-4435-afc6-9faeea4c7c8f', // dashboard dos espaços
        'text' => 'Saiba os números de espaços cadastrados, quantos são criados mensalmente, por onde estão distribuídos no território e outras informações.',
        'title' => 'Painel sobre espaços',
        'entity' => 'Space'
    ],
    'painel-oportunidades' => [
        'link' => 'https://metabase.mapas.tec.br/public/dashboard/496d0b03-0476-4497-9a3d-719198cfe083', //dashboard das oportunidade
        'text' => 'Tenha acesso ao número de oportunidades e editais cadastrados, a quantidade de pessoas participantes inscritas, o perfil demográfico e mais informações.',
        'title' => 'Painel sobre oportunidades',
        'entity' => 'Opportunity'
    ],
],

```

## Instalação

Baixar o plugin:

`git submodule update`

Entrar no container

`docker exec -it HASH_CONTAINER bash`

Instalar dependências e realizar o build

`cd src && pnpm install && pnpm run build`

2025-01-08 21:46 UTC, fernandolordao requested changes
Ver comentários no código fonte.

2025-01-08 21:46 UTC, fernandolordao commented on .gitmodules
> +	url = https://github.com/RedeMapas/plugin-Metabase
Considerar o repositório clonado pelo MinC e disponibilizado em https://github.com/culturagovbr/plugin-Metabase

2025-01-10 17:09 UTC, vicmagpac commented on .gitmodules
> +	url = https://github.com/RedeMapas/plugin-Metabase
Obrigado pelo retorno @fernandolordao. Realizamos a atualização da URL do submodule.

2025-03-13 15:29 UTC, gabrielribeirobizerril commented
Serão 2 painéis, sendo eles: 1) Ações culturais e Instrumentos de Fomento; 2) Agentes culturais. Isso foi acordado com o responsável pelos painéis do lado do TED (Alexandre) e pela equipe de desenvolvimento. 
O painel de "Espaços" não está mais no escopo. Sendo assim a tab de indicadores para Espaços não precisa ser implementada.

2025-03-13 16:38 UTC, vicmagpac commented
@fernandolordao @gabrielribeirobizerril atualização realizada com sucesso.

- Os links dos dashboards corretos foram adicionados nas configurações do plugin do metabase.

@fernandolordao é necessário atualizar o repositório https://github.com/culturagovbr/plugin-Metabase de vocês com a versão mais recente do https://github.com/RedeMapas/plugin-Metabase para que o dashboard de espaços seja removido da tela de espaços.

2025-05-29 00:30 UTC, lucasfullstackdev approved these changes

2025-06-05 14:29 UTC, lucasfullstackdev commented
Aprovado pela área requisitante

2025-06-05 14:33 UTC, merged