Implementa funcionalidade de gestão do plano de trabalho compatível com a versão v7.6.0
culturagovbr/mapadacultura pull request #40
Opened 2024-12-26 17:02 UTC by vicmagpac

## Descrição

O PR tem como objetivo realizar a implementação da funcionalidade do plano de trabalho. A funcionalidade consiste em permitir para o gestor de oportunidade configurar uma fase da oportunidade especificando os detalhes e características do plano de trabalho que deve ser preenchido no momento da inscrição caso habilitado.

## Principais implementações:

### Visão do gestor de oportunidade

- Habilita o plano de trabalho e a duração.
![image](https://github.com/user-attachments/assets/08047ad9-de79-4dd3-ae6c-2eaaf9d309d5)

- Habilitar configurações das metas. 
![image](https://github.com/user-attachments/assets/fb1ffa55-b55d-4e57-996f-6f5f9d7a29e3)

- Habilita configurações das entregas e de monitoramento
![image](https://github.com/user-attachments/assets/f57f58e8-8a19-4b72-9ff8-866508e2c286)

### Visão do proponente

- Preenchimento do plano de trabalho no momento da inscrição
![image](https://github.com/user-attachments/assets/7241f017-3569-4f11-8562-4210d1c8d660)

- Preenchimento da meta no momento da inscrição
![image](https://github.com/user-attachments/assets/2ab1610d-41dd-4030-97c0-fbc5d4d6d7c5)

- Preenchimento da entrega da meta no momento da inscrição
![image](https://github.com/user-attachments/assets/6dd161a0-f266-4b60-8111-29fac0780695)

- Detalhes da inscrição por parte do proponente
![image](https://github.com/user-attachments/assets/c21c7d86-0975-4b58-956d-d184e38c5b76)

- Imprimir ficha de inscrição
![image](https://github.com/user-attachments/assets/28c56563-63dd-4ea5-9093-1416b01af86e)

2025-01-15 15:47 UTC, fernandolordao requested changes
Sugiro rever a criação do arquivo `src/modules/OpportunityWorkplan/db-updates.php` ponderando dois fatores: a importância do desacoplamento de código (que é desejável) e a garantia da sequência dos scripts no que se refere a diferentes versões.
Suponha, futuramente, diversos módulos com seus próprios `db-updates.php`. Como iremos garantir que esses diversos `db-updates.php` sejam executados na sequência adequada? Podemos garantir que o atual `db-updates.php` será executado antes de outro que precisa sucedê-lo?

2025-01-15 15:47 UTC, fernandolordao commented on src/modules/OpportunityWorkplan/db-updates.php
Verificar observações do comentário principal sobre este arquivo.

2025-01-15 16:07 UTC, vicmagpac commented on src/modules/OpportunityWorkplan/db-updates.php
A abordagem atual, em que o db-updates.php está atrelado ao ciclo de vida da aplicação, tem suas vantagens, especialmente em termos de simplicidade e confiabilidade no momento da execução. Essa estrutura garante que:

Desacoplamento dos Módulos:
Ao centralizar a lógica de atualização no próprio módulo, cada módulo mantém o controle de suas atualizações de banco de dados, evitando dependências desnecessárias com outros módulos ou sistemas externos.

Execução Única:
O script db-updates.php é projetado para ser executado apenas uma vez, evitando reprocessamentos desnecessários e garantindo que a lógica de atualização do banco de dados seja aplicada de forma controlada.

Execução Condicionada à Inicialização:
O script será executado somente quando a aplicação iniciar e o ciclo normal de inicialização incluir a lógica de atualização do banco de dados. Isso elimina a necessidade de um mecanismo separado para orquestrar a execução de scripts, mantendo o processo simples e direto.

Exemplos de arquivos db-update que já usam esse padrão:

- src/modules/OpportunityPhases/db-updates.php
- src/themes/BaseV1/db-updates.php
- src/themes/Subsite/db-updates.php
- src/modules/Opportunities/db-updates.php
- src/modules/UserManagement/db-updates.php

**É importante especificar que a implementação foi baseado nos módulos e plugins já existentes no mapa garantindo assim a padronização.**

2025-01-15 20:20 UTC, vicmagpac commented on src/modules/OpportunityWorkplan/db-updates.php
@fernandolordao atualização realizada e testada com sucesso. Realizamos a mudança para que o update seja realizado no core ao invés do db-update dentro do módulo.
A alteração pode ser verificada aqui no commit: https://github.com/culturagovbr/mapadacultura/pull/40/commits/6c8d4600fd04ab00e5f245aa697a660b55d83389

2025-01-15 21:25 UTC, fernandolordao reviewed
Publicado para teste pela área requisitante.

2025-01-22 22:04 UTC, fernandolordao commented
Fechando para seguir com o PR #45 que é uma versão nova deste aqui.

2025-01-22 22:04 UTC, closed without merging